In [2]:
import numpy as np


In [8]:
# create from list
arr = np.array([1,2,3,4,5])
print(arr,type(arr)),

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2)),arr2.dtype

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12,]])
print(arr2D,arr2D.shape,arr2D.ndim)

[1 2 3 4 5] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3) 2


In [ ]:
# Create from scratch
arr1 = np.zeros((2,3), dtype ="int64")
print(arr1,arr1.shape)

arr2 = np.ones((2,8))
print(arr2,arr2.shape)

arr3 =np.full((5,3),18)
print(arr3,arr3.shape)

arr4 = np.eye(5)# eye means identity matrix
print(arr4,arr4.shape)# USED IN MATHEMATICS HEAVILY

arr5 = np.arange(1,10,2)
print(arr5,arr5.shape)

arr6 = np.linspace(1,10,5)# EVENLY SPACED NUMBERS BETWEEN 1 AND 10
print(arr6,arr6.shape)

# This method is used to create an array from scratch with random values

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]] (2, 8)
[[18 18 18]
 [18 18 18]
 [18 18 18]
 [18 18 18]
 [18 18 18]] (5, 3)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] (5, 5)
[1 3 5 7 9] (5,)
[ 1.    3.25  5.5   7.75 10.  ] (5,)


In [ ]:
# Properties of array
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12,]])

print(arr.shape)# dimensions of array
print(arr.size)# total number of elements in array
print(arr.dtype)# data type of array
print(arr.ndim)# number of dimensions of array

arr1 = np.array([1,2,3,4,5],dtype="float64")
print(arr1,arr1.dtype)

float_arr = arr.astype(np.float64)# convert the data type of array to float64
print(float_arr,float_arr.dtype)

(4, 3)
12
int64
2
[1. 2. 3. 4. 5.] float64
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]] float64


In [ ]:
# Operations on array

# 1. Reshaping an array
# Reshaping an array means changing the shape of the array without changing the data. The reshape() method is used to reshape an array.
# Indexing(1D & 2D array)
# Fancy and boolean indexing
# Slicing
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr,reshaped_arr.shape)

flattened = arr.flatten()# flatten the array to 1D array
print(flattened,flattened.shape)



[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [30]:
# Indexing 
# arr = np.array([1,2,3,4,5])
arr = np.array([[1,2,3],[4,5,6]])

print(arr[1][0])



4
