In [6]:
# Data types in python 
'''
. Integers : int32, int64
. Floating point nums: float32,float64
. Boolean : bool
. Complex nums: complex64, complex128
. String :S(byte-str) & U(unicode-str)
. Object:generic python objectx - obhject
'''
import numpy as np
arr1 = np.array([3 +5j ])
arr2 =np.array([2,3j])
print(arr1,arr1.dtype)
print(arr1 +arr2)
print(arr1 - arr2)


[3.+5.j] complex128
[5.+5.j 3.+8.j]
[1.+5.j 3.+2.j]


In [9]:
# Ṃulti-dimensional arrays
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D,axis=0)
print(sum_of_columns)

sum_of_rows =np.sum(arr2D ,axis=1)
print(sum_of_rows)

# slicing 
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [13]:
# 3D_array
arr3D =np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2 x 3 x2
print(arr3D,arr3D.shape)

# indixing
print(arr3D[1,1,0])

# slicing
print(arr3D[:,0,:]) #first row from both layers

arr3D[: ,0,:] = 99

print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [14]:
arr = np.array([[1,2],[3,4]])

print(np.mean(arr))
print(np.std(arr))


2.5
1.118033988749895


In [6]:
# Mathematical function
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.argmin(arr))
print(np.argmax(arr))

28
5040
1
7
4.0
2.0
4.0
0
6


In [7]:
# Power function

arr = np.array([1,2,3,4,5,6])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))



[ 1  4  9 16 25 36]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  1   8  27  64 125 216]


In [ ]:
# log function

arr = np.array([1,2,3,4,5,6])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))



[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125]
[0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [12]:
# Rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1,2,3,4,5,6])
print(np.unique(arr))
print(np.sort(arr))

print(np.abs(arr))


3.0
4.0
3.0
3.0
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
